"$schema" = 'https://starship.rs/config-schema.json'

palette = "custom"

# Inserts a blank line between shell prompts
add_newline = false
format = """
[╭─](fg:line)[ ](bg:bg)\
$os\
[  ](fg:separator bg:bg)\
$directory\
[ ](bg:bg)\
([ ](fg:separator bg:bg)\
$git_branch\
$git_commit\
$git_state\
$git_status)\
$time\
[](fg:bg)\
$fill\
$terraform\
[](fg:bg)\
$status\
[─╮](fg:line)($shell)
[╰─](fg:line)$sudo$character"""

right_format = "[─╯](fg:line)"

[palettes.custom]
bg = "#1c1c1c"
fg = "#eeeee7"
line = "#444444"
separator = "#6c6c6c"

[character]
format = " "

[fill]
symbol = " "

[shell]
disabled = false
format ="[$indicator]($style)"
bash_indicator = ""
zsh_indicator = " "
fish_indicator = ""

[os]
disabled = false
format = "[$symbol](fg:fg bg:bg)"

[os.symbols]
Ubuntu = "󰕈"
Macos = ""
Windows = ""
NixOS = ""

[directory]
format = '[  $path]($style)[$read_only]($read_only_style)'
style = "fg:cyan bg:bg"

[git_branch]
format = '[$symbol$branch ]($style)[$compare]($compare_style)'
symbol = " "
style = "fg:green bg:bg"

[git_commit]
format = '[\($hash$tag\) ]($style)'
style = "fg:green bg:bg"

[git_state]
style = "fg:red bg:bg"
format = '[$state( $progress_current/$progress_total) ]($style)'
merge = "merge"
rebase = "rebase"
revert = "revert"
bisect = "bisect"
cherry_pick = "cherry-pick"
am = "apply-mailbox"
am_or_rebase = "apply-mailbox/rebase"

[git_status]
format = '$all_status$ahead_behind'
untracked = "[?$count ](fg:cyan bg:bg)"
stashed = "[*$count ](fg:green bg:bg)"
modified = "[!$count ](fg:yellow bg:bg)"
staged = "[+$count ](fg:yellow bg:bg)"
renamed = "[~$count ](fg:yellow bg:bg)"
deleted = "[-$count ](fg:red bg:bg)"

[status]
disabled = false
style = "bg:bg"
format = "[$symbol$maybe_int ]($style)"
success_symbol = "[](fg:green bg:bg)"
map_symbol = true
